name: Main

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Waaatanuki/asset
          path: asset
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: pnpm
      # - name: Install
      #   run: cd ../asset
      - name: Update1
        run: pnpm run update
