name: Main

permissions:
  contents: write

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: learngit
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: Waaatanuki/asset
          path: ../asset
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Update1
        run: pnpm run update
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ../asset
          destination-github-username: Waaatanuki
          destination-repository-name: asset
          user-email: watanukipublic@gmail.com
          target-branch: main
          commit-message: action
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: Waaatanuki
          commit_user_email: watanukipublic@gmail.com
          commit_author: Waaatanuki <watanukipublic@gmail.com>
          commit_message: chore
