name: Main

permissions:
  contents: write

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout library
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: Waaatanuki/library

      - name: Checkout asset
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: Waaatanuki/asset
          path: asset
